class UpdateProductIndexFromListingSource
  include Interactor

  def call
    result = WriteProductToIndex.call(listing: context.listing)

    # Only use the product generated by the WriteProductToIndex interactor if
    # it was either found in the index (by upc, mpn, or sku) or created and saved to the index.
    # Otherwise, throw it out, so that SetProduct can try to find a best match.
    context.product = result.product if result.product.try(:persisted?)
  end
end