# Add application configuration variables here, as shown below.
production:
  AWS_ACCESS_KEY_ID: 12334
  AWS_SECRET_ACCESS_KEY: 12334
  AIRBRAKE_API_KEY: 12334
  SIDEKIQ_REDIS_URL: '12334'
  IRONGRID_REDIS_URL: '12334'
  IRONSIGHTS_REDIS_URL: '12334'
  ELASTICSEARCH_URL_LOCAL: "12334"
  ELASTICSEARCH_URL_REMOTE: "12334"
development:
  AWS_ACCESS_KEY_ID: 12334
  AWS_SECRET_ACCESS_KEY: 12334
  ELASTICSEARCH_URL_LOCAL: "http://localhost:9200/"
  ELASTICSEARCH_URL_REMOTE: "http://localhost:9200/"
staging:
  AWS_ACCESS_KEY_ID: 12334
  AWS_SECRET_ACCESS_KEY: 12334
  ELASTICSEARCH_URL_LOCAL: "http://localhost:9200/"
  ELASTICSEARCH_URL_REMOTE: "http://localhost:9200/"
test:
  AWS_ACCESS_KEY_ID: 12334
  AWS_SECRET_ACCESS_KEY: 12334
  ELASTICSEARCH_URL_LOCAL: "http://localhost:9200/"
  ELASTICSEARCH_URL_REMOTE: "http://localhost:9200/"
cucumber:
  AWS_ACCESS_KEY_ID: 12334
  AWS_SECRET_ACCESS_KEY: 12334
  ELASTICSEARCH_URL_LOCAL: "http://localhost:9200/"
  ELASTICSEARCH_URL_REMOTE: "http://localhost:9200/"
