production:
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 200
  url: Figaro.env.database_url

staging:
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 25
  url: Figaro.env.database_url

development:
  adapter: postgresql
  encoding: unicode
  pool: 15
  database: scoperrific_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: scoperrific_test

cucumber:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: scoperrific_test
