development:
  adapter: postgresql
  encoding: unicode
  pool: 15
  database: scoperrific_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: scoperrific_test

cucumber:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: scoperrific_test
