production:
  irongrid_redis_pool:
    pool: 30
    url: irongrid_redis_url
  stretched_redis_pool:
    pool: 25
    url: stretched_redis_url
  ironsights_redis_pool:
    pool: 15
    url: ironsights_redis_url
staging:
  irongrid_redis_pool:
    pool: 5
    url: irongrid_redis_url
  stretched_redis_pool:
    pool: 5
    url: stretched_redis_url
  ironsights_redis_pool:
    pool: 1
    url: ironsights_redis_url
development:
  irongrid_redis_pool:
    pool: 5
    url: irongrid_redis_url
  stretched_redis_pool:
    pool: 5
    url: stretched_redis_url
  ironsights_redis_pool:
    pool: 5
    url: ironsights_redis_url
test:
  irongrid_redis_pool:
    pool: 2
    url: irongrid_redis_url
  stretched_redis_pool:
    pool: 2
    url: stretched_redis_url
  ironsights_redis_pool:
    pool: 2
    url: ironsights_redis_url


