production:
  ironsights:
    database: 0
    url:      redis_url
    pool:     5
  sidekiq:
    database: 1
    url:      redis_url
  irongrid:
    database: 2
    url:      redis_url
    pool:     5
  stretched:
    database: 5
    url:      redis_url
    pool:     30
staging:
  ironsights:
    database: 6
    url:      redis_url
    pool:     1
  sidekiq:
    database: 7
    url:      redis_url
  irongrid:
    database: 8
    url:      redis_url
    pool:     5
  stretched:
    database: 10
    url:      redis_url
    pool:     5
development:
  ironsights:
    database: 0
    url:      redis_url
    pool:     5
  sidekiq:
    database: 1
    url:      redis_url
  irongrid:
    database: 2
    url:      redis_url
    pool:     5
  stretched:
    database: 5
    url:      redis_url
    pool:     30
test:
  ironsights:
    database: 6
    url:      redis_url
    pool:     1
  sidekiq:
    database: 7
    url:      redis_url
  irongrid:
    database: 8
    url:      redis_url
    pool:     5
  stretched:
    database: 10
    url:      redis_url
    pool:     5


