production:
  pool: 20
  databases:
    ironsights: 0
    sidekiq:    1
    irongrid:   2
    stretched:  5
staging:
  pool: 5
  databases:
    ironsights: 6
    sidekiq:    7
    irongrid:   8
    stretched:  10
development:
  pool: 5
  databases:
    ironsights: 0
    sidekiq:    1
    irongrid:   2
    stretched:  5
test:
  pool: 5
  databases:
    ironsights: 6
    sidekiq:    7
    irongrid:   8
    stretched:  10


